name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHROME_OPTIONS: "--remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080"
      UI_HOST: "https://www.saucedemo.com/"
      ADMIN_USERNAME: ${{ secrets.USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.PASSWORD }}
      CI_TOKEN: ${{ secrets.CI_TOKEN}}

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Run tests
        run: |
          python -m pytest --alluredir=allure-results -sv

      - name: Copy history from gh-pages to allure-results
        run: |
          if [ -d "./.github/gh-pages/history" ]; then
            sudo mkdir -p allure-results/history
            sudo cp -R ./.github/gh-pages/history/* allure-results/history/
          fi

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Move Allure report to history
        run: |
          date=$(date +"%Y-%m-%d_%H-%M-%S")
          if [ ! -d "docs/allure-report-history" ]; then
            sudo mkdir -p docs/allure-report-history
            sudo mv allure-report docs/allure-report-history/allure-report-$date
          fi

      - name: Update GitHub Pages with the latest report
        run: |
          latest_report=$(ls -d docs/allure-report-history/allure-report-* | sort -r | head -n 1)
          ln -s $latest_report docs/allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: docs
          clean: false

