name: CI Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Run tests
        env:
          CHROME_OPTIONS: "--remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080"
          UI_HOST: "https://www.saucedemo.com/"
          ADMIN_USERNAME: ${{ secrets.USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python -m pytest -sv --alluredir=allure-results

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history
          if [ -d "./.github/gh-pages/history" ] && [ "$(ls -A ./.github/gh-pages/history)" ]; then
            sudo cp -R allure-report/history/* ./.github/gh-pages/history/
          fi

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Update Allure history
        run: |
          sudo mkdir -p ./.github/gh-pages/history
          if [ -d "allure-report/history" ] && [ "$(ls -A allure-report/history)" ]; then
            sudo cp -R allure-report/history/* ./.github/gh-pages/history/
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
