name: CI Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          CHROME_OPTIONS: "--remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080"
          UI_HOST: "https://www.saucedemo.com/"
          ADMIN_USERNAME: ${{ secrets.USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          pytest -sv --alluredir=allure-results --disable-warnings -q

      - name: Get Allure history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          allure_report: allure-report
          gh_pages: gh-pages
          ref: gh-pages
          path: gh-pages
          keep_reports: 60

      - name: Commit allure_report to Github Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          publish_dir: allure-history

      - name: Update secret with run number
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.CI_TOKEN }}" \
            -d '{"secret": {"name": "RUN_NUMBER", "value": "${{ github.run_number }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets