name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHROME_OPTIONS: "--remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080"
      UI_HOST: "https://www.saucedemo.com/"
      ADMIN_USERNAME: ${{ secrets.USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.PASSWORD }}
      CI_TOKEN: ${{ secrets.CI_TOKEN}}

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Run tests
        run: |
          python -m pytest --alluredir=allure-results -sv

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          git reset --hard

      - name: Upload Allure report to GitHub Pages
        run: |
          mkdir -p docs/allure-report
          mv allure-report/* docs/allure-report/
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git config --global credential.helper "store"
          echo "https://x-access-token:${{ secrets.CI_TOKEN }}@github.com" > ~/.git-credentials
          git add docs/allure-report/
          git commit -m 'Update Allure report'
          git push origin gh-pages
