name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CHROME_OPTIONS: "--remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080"
      UI_HOST: "https://www.saucedemo.com/"
      ADMIN_USERNAME: ${{ secrets.USERNAME }}
      ADMIN_PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          apk update && \
          apk add openjdk11-jre curl tar && \
          curl -o allure-2.13.8.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.8/allure-commandline-2.13.8.tgz && \
          tar -zxvf allure-2.13.8.tgz -C /opt/ && \
          ln -s /opt/allure-2.13.8/bin/allure /usr/bin/allure && \
          rm allure-2.13.8.tgz

      - name: Run tests
        run: |
          python -m pytest --alluredir=allure-results -sv

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report to GitHub Pages
        run: |
          mkdir -p docs/allure-report
          mv allure-report/* docs/allure-report/
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/allure-report/
          git commit -m 'Update Allure report'
          git push origin gh-pages
