name: CI Pipeline

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Allure Commandline
        run: |
          curl -o allure.tgz -L https://github.com/allure-framework/allure2/releases/download/2.18.1/allure-2.18.1.tgz
          tar -zxvf allure.tgz
          sudo mv allure-2.18.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure

      - name: Run tests
        env:
          CHROME_OPTIONS: "--remote-allow-origins=*;--disable-gpu;--no-sandbox;--disable-dev-shm-usage;--headless=new;--window-size=1920,1080"
          UI_HOST: "https://www.saucedemo.com/"
          ADMIN_USERNAME: ${{ secrets.USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python -m pytest -sv --alluredir=allure-results
      
      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.CI_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
